#!/bin/bash

INSTANCE_DATA_FILE=$1

if [ "$WERCKER_RESULT" = "failed" ]; then
  if [ -z "$TERMINATE_FAILED_TEST_INSTANCE" ]; then
    exit 0
  fi
fi

SCRIPTS=$(dirname $0)/..

function destroy_old_stack() {
  while read INSTANCE_DATA; do
    $SCRIPTS/test-instance/unprotect $INSTANCE_DATA
    $SCRIPTS/test-instance/terminate $INSTANCE_DATA
  done < $INSTANCE_DATA_FILE
}

function destroy_new_stack() {
  declare testId=$(cat test_id)
  curl --silent --verbose \
       --request POST \
       --header "X-Cebeci-Test-Env-Auth: $CEBECI_TEST_ENV_AUTH_PASSWORD" \
       --data "testId=`cat test_id`" \
       http://cebeci.koding.com/cebeci/api/env/test/terminate
}

destroy_old_stack
for dir in $(ls -1 $TEST_ENV_DIR); do
  pushd $TEST_ENV_DIR/$dir
  destroy_new_stack
  popd
done
