#!/bin/bash

SCRIPTS_DIR=$WERCKER_ROOT/scripts

set -o errexit

BRANCH=${BRANCH:-$(git rev-parse --abbrev-ref HEAD)}
REVISION=${REVISION:-$(git rev-parse HEAD)}

function create_old_stack() {
  declare options=$($SCRIPTS_DIR/test-instance/get-options)
  options="--branch-name $BRANCH $options"
  echo $options

  $SCRIPTS_DIR/test-instance/launch $options > INSTANCE_DATA
  cat INSTANCE_DATA
}

function create_new_stack() {
  curl --silent --verbose \
       --request POST \
       --header "X-Cebeci-Test-Env-Auth: $CEBECI_TEST_ENV_AUTH_PASSWORD" \
       --data "sha=$REVISION" --data "branch=$BRANCH" \
       http://cebeci.koding.com/cebeci/api/env/test/create |
    jq -r '.testId, .ip, .hostname' > info

  read testId ip hostname < info
  echo $testId > test_id
  echo $ip > ip
  echo $hostname > hostname
}

create_old_stack

for i in $(seq 58); do
  mkdir -p $TEST_ENV_DIR/$i
  pushd $TEST_ENV_DIR/$i
  create_new_stack
  popd
done

exit 0
