#!/bin/bash

SCRIPTS_DIR=$WERCKER_ROOT/scripts

set -o errexit

BRANCH=${BRANCH:-$WERCKER_GIT_BRANCH}
REVISION=${REVISION:-$WERCKER_GIT_COMMIT}

function create_old_stack() {
  declare options=$($SCRIPTS_DIR/test-instance/get-options)
  options="--branch-name $BRANCH $options"
  echo $options

  $SCRIPTS_DIR/test-instance/launch $options > INSTANCE_DATA
  cat INSTANCE_DATA
}

create_old_stack

exit 0
