#!/bin/bash

set -o errexit

HOSTNAME="`ec2metadata --instance-id`.test.ci.koding.io"

export HOME=/root/
export REPOSITORY_PATH='/opt/koding'

export CI="true"
export WERCKER="true"

export CONFIG_DEBUGMODE="true"

ulimit -n 10240

cd $REPOSITORY_PATH

git config user.email 'sysops@koding.com'
git config user.name 'Koding Bot'

TEST_EXTRAS="--no-start-selenium --url http://$HOSTNAME" \
  make -C client/test build

pip install docker-compose

docker-compose -f docker-compose-init.yml run init configure \
               --config dev --host $HOSTNAME \
               --hostname $HOSTNAME --publicPort 80 \
               --disable-segment

docker-compose up -d

export TEST_VENDOR=$REPOSITORY_PATH/client/test/vendor

export DISPLAY=:0
Xvfb $DISPLAY -shmem -screen 0 1440x900x16 &
java -jar $TEST_VENDOR/selenium-server-standalone.jar \
     -host 0.0.0.0 \
     -port 42420 \
     -Dwebdriver.gecko.driver=$TEST_VENDOR/geckodriver/linux64/geckodriver \
     &> $REPOSITORY_PATH/.logs/selenium-host.log &

export DISPLAY=:1
Xvfb $DISPLAY -shmem -screen 1 1440x900x16 &
java -jar $TEST_VENDOR/selenium-server-standalone.jar \
     -host 0.0.0.0 \
     -port 42421 \
     -Dwebdriver.gecko.driver=$TEST_VENDOR/geckodriver/linux64/geckodriver \
     &> $REPOSITORY_PATH/.logs/selenium-participant.log &

sleep 10

x11vnc -passwd secret -display :0 -N -forever &
x11vnc -passwd secret -display :1 -N -forever &

exit 0
